import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  static const String _languageKey = 'app_language';
  static const String _hasSelectedLanguageKey = 'has_selected_language';
  String _currentLanguage = 'tr';
  bool _hasSelectedLanguage = false;
  bool _isInitialized = false;

  String get currentLanguage => _currentLanguage;
  bool get hasSelectedLanguage => _hasSelectedLanguage;
  bool get isInitialized => _isInitialized;

  LanguageProvider() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString(_languageKey) ?? 'tr';
    _hasSelectedLanguage = prefs.getBool(_hasSelectedLanguageKey) ?? false;
    _isInitialized = true;
    notifyListeners();
  }

  Future<void> setLanguage(String lang) async {
    _currentLanguage = lang;
    _hasSelectedLanguage = true;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, lang);
    await prefs.setBool(_hasSelectedLanguageKey, true);
    notifyListeners();
  }

  // String getter helper
  String getString(String key) {
    if (_currentLanguage == 'en') {
      return _enStrings[key] ?? _trStrings[key] ?? key;
    }
    return _trStrings[key] ?? _enStrings[key] ?? key;
  }

  /// `{name}` yer tutucularını değiştirir.
  String format(String key, Map<String, String> values) {
    var s = getString(key);
    for (final e in values.entries) {
      s = s.replaceAll('{${e.key}}', e.value);
    }
    return s;
  }

  static const Map<String, String> _trStrings = {
    'settings': 'Ayarlar',
    'general': 'Genel',
    'language': 'Dil / Language',
    'sound_vibration': 'Ses ve Titreşim',
    'sound': 'Ses',
    'sound_subtitle': 'Oyun seslerini aç/kapat',
    'vibration': 'Titreşim',
    'vibration_subtitle': 'Oyun içi titreşim bildirimleri',
    'notifications': 'Bildirimler',
    'notifications_subtitle': 'Push bildirimlerini aç/kapat',
    'legal': 'Yasal',
    'terms': 'Kullanım Şartları',
    'privacy': 'Gizlilik Politikası',
    'other': 'Diğer',
    'support': 'Destek',
    'support_subtitle': 'Yardım ve geri bildirim',
    'guide': 'Rehber',
    'replay_tutorial': 'Tutorial\'ı Tekrar İzle',
    'promo_code': 'Promosyon Kodu Kullan',
    'logout': 'Çıkış Yap',
    'delete_account': 'Hesabı Sil',
    'version': 'Versiyon',
    'cancel': 'İptal',
    'apply': 'Uygula',
    'quit_duel_title': 'Pes Etmek Üzeresin!',
    'quit_duel_confirm': 'Yarışmadan çıkarsan yenilgiyi kabul etmiş sayılırsın ve puan kaybedersin. Çıkmak istediğine emin misin?',
    'confirm': 'Yenilgiyi Kabul Et',
    'confirm_logout': 'Çıkış yapmak istediğinize emin misiniz?',
    'confirm_delete': 'Hesabınızı ve tüm verilerinizi kalıcı olarak silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
    'welcome_title': 'Hoş Geldin',
    'daily_bonus_ready': 'GÜNLÜK BONUSUN HAZIR',
    'claim_rewards': 'ÖDÜLLERİ AL!',
    'coins_unit_label': 'Altın',
    'new_reward': 'YENİ ÖDÜL!',
    'next_reward': 'Sonraki Ödül →',
    'great_confetti': 'Harika! 🎊',
    'daily_login_rewards': 'Günlük Giriş Ödülleri',
    'streak_message': 'Kesintisiz {streak} gündür buradasın!',
    'grand_prize': 'Büyük Ödül',
    'day_label': 'Gün',
    'ad_failed_or_skipped': 'Reklam yüklenemedi veya atlandı.',
    'your_answer_short': 'Senin',
    'saved': 'Kayıtlı',
    'word_selected_count': '{count} kelime seçildi',
    'duel_mode': 'Duel Modu',
    'practice_mode': 'Practice',
    'daily_123': 'Daily 123',
    'achievements': 'Başarılar',
    'profile': 'Profil',
    'shop': 'Mağaza',
    'stats': 'İstatistikler',
    'leaderboard': 'Liderlik Tablosu',
    'practice_info': 'Kendi seviyene uygun kelimelerle pratik yap!',
    'duel_info': 'Arkadaşlarınla veya botla düello yap!',
    'play': 'Oyna',
    'start': 'Başlat',
    'next': 'İleri',
    'skip': 'Atla',
    'back': 'Geri',
    'level_test': 'SEVİYE TESTİ',
    'intro_skip': 'Atla',
    'continue_practice': 'Çalışmaya Devam Et',
    'duel_locked_message': 'Duel modunu açmak için önce 3 adet Practice oturumu tamamlamalısın.',
    'daily_locked_message': 'Bugünkü Daily 123 hakkını kullandın! Yarın tekrar gel 🎲',
    'daily_123_subtitle': 'Günün rekorunu kırmak için yarış',
    'league_a': 'A Ligi',
    'league_b': 'B Ligi',
    'league_c': 'C Ligi',
    'your_rank': 'Senin Sıran',
    'your_rank_in': 'Senin Sıran ({category}):',
    'leaderboard_rank_score_label': 'Sıra puanı',
    'leaderboard_row_secondary_hint': 'İstatistikler (sıra puanı değil)',
    'leaderboard_badge_wins': 'Galibiyet',
    'leaderboard_badge_course': 'Kurs seviyesi',
    'no_data_yet': 'Henüz veri yok',
    'search_username': 'Kullanıcı adı ile ara...',
    'search_min_chars': 'Aramak için en az 3 karakter girin',
    'user_not_found': 'Kullanıcı bulunamadı',
    'global': 'Global',
    'powerups': 'Güçlendiriciler',
    'packs': 'Paketler',
    'customize': 'Özelleştir',
    'coins': 'Coinler',
    'premium': 'Premium',
    'market': 'Market',
    'buy': 'Satın Al',
    'owned': 'Sahip Olundu',
    'equipped': 'Kuşanıldı',
    'select': 'Seç',
    'resume_game': 'OYUNA DEVAM ET',
    'resume_duel': 'DÜELLOYA DEVAM ET',
    'success': 'Başarı',
    'my_words': 'Kelimelerim',
    'home': 'Ana Sayfa',
    'ranking': 'Sıralama',
    'completed': 'Tamamlandı',
    'duel_unlock_progress': '3 Oturum Tamamla Düelloya Başla',
    'keep_practicing': 'Seviyene Göre Çalışmaya Devam Et',
    'duel_desc': 'Arkadaşlarına veya bota karşı yarış',
    'duel_remaining': 'Son {kalan} oturum kaldı!',
    'level_test_desc': 'Başlangıç seviyeni belirlemek için 3 oturum tamamla',
    'stats_and_settings': 'İstatistikler ve Ayarlar',
    'points': 'Puan',
    'awards': 'Ödüller',
    'statistics': 'İstatistikler',
    'friends': 'Arkadaşlar',
    'premium_feature': 'Premium Özellik',
    'premium_info': 'Profil fotoğrafı yükleme özelliği sadece Premium üyelerimiz içindir.',
    'language_passport_title': 'Dil Pasaportu',
    'language_passport_subtitle': 'Öğrenme haritan ve uzmanlık alanların',
    'close': 'Kapat',
    'go_premium': 'Premium Ol',
    'profile_updated': 'Profil fotoğrafı başarıyla güncellendi! ✨',
    'upload_failed': 'Yükleme başarısız oldu.',
    'change_appearance': 'Görünümünü Değiştir',
    'upload_profile_photo': 'Profil Fotoğrafı Yükle',
    'only_premium': 'Sadece Premium üyeler için',
    'purchased_avatars': 'Satın Alınan Avatarlar',
    'no_avatars': 'Henüz avatar satın almamışsın.',
    'go_to_market': 'Markete Git',
    'frames': 'Çerçeveler',
    'no_frames': 'Henüz çerçeve satın almamışsın.',
    'none': 'Yok',
    'info_how_to_play': '🎯 Nasıl Oynanır?',
    'info_practice_body': 'Her oturumda 10 soru cevaplayarak kelime bilginizi pekiştirirsiniz. Sorular seviyenize göre otomatik olarak belirlenir.',
    'info_level_system': '📊 Seviye Sistemi',
    'info_level_system_body': '• 2 oturum üst üste %70+ başarı: Üst seviye\n• 2 oturum üst üste %30- başarı: Alt seviye\n• Seviyeler: A1 → A2 → B1 → B2 → C1 → C2',
    'info_scoring': '💰 Puanlama',
    'info_scoring_body': '• A: +5 / -3 | B: +10 / -6 | C: +15 / -9\n• Hızlı cevaplar ekstra puan kazandırır!',
    'info_got_it': 'Anladım!',
    'info_duel_title': 'Duel Modu',
    'info_duel_body': 'Rakibinle 1v1 kelime yarışması! Bot, online rakip veya arkadaşlarınla 10 soruluk maçlarda yarış. En yüksek skoru alan kazanır!',
    'info_lp_system': '📊 LP Puanlama Sistemi',
    'info_lp_system_body': '• Galibiyet: +5 ile +50 Puan\n• Mağlubiyet: -5 ile -50 Puan\n• Güçlü rakibi yenmek daha çok puan kazandırır.',
    'info_modes': '🤖 Mod Seçenekleri',
    'info_modes_body': '• Online: Rastgele bir oyuncuyla eşleş\n• Bot: AI rakibe karşı pratik yap\n• Arkadaş: Arkadaşını davet et',
    'info_daily_title': 'Daily 123',
    'info_daily_body': 'Günde bir kez oynayabileceğin özel yarışma! A1\'den başlarsın, doğru bildikçe yükselirsin.',
    'info_daily_scoring': '📊 Puanlama',
    'info_daily_scoring_body': 'Sadece seviye puanları geçerlidir. Seri veya hız bonusu yoktur.',
    'info_dynamic_level': 'Dinamik Seviye Sistemi',
    'info_dynamic_level_body': 'Her doğru cevapta seviyen bir kademe yükselir, yanlış cevapta ise bir kademe düşer. Zorlaştıkça ödül artar!',
    'info_scoring_table': 'Doğru/Yanlış Puan Tablosu',
    'info_important': '⚠️ Önemli',
    'info_important_body': 'Her gün gece yarısı sıfırlanır.',
    'select_duel_mode': 'Duel Modu Seç',
    'how_to_compete': 'Nasıl yarışmak istersin?',
    'lugo_duel_title': 'LUGO DUEL',
    'lugo_duel_desc': 'Online oyuncularla yarış (LP Etkiler)',
    'bot_duel_title': 'BOT DUEL',
    'bot_duel_desc': 'Kendi seviyende bota karşı yarış',
    'buddy_duel_title': 'ARKADAŞ DUEL',
    'buddy_duel_desc': 'Arkadaşlarınla yarış (LP Etkiler)',
    'friend_duel_title': 'ARKADAŞ DUEL',
    'friend_duel_desc': 'Arkadaş listenden birini davet et',
    'start_practice_btn': 'Pratiğe Başla',
    'weekly_practice_bar_title': 'Haftalık Pratik Puanı',
    'weekly_practice_milestone_snack':
        'Haftalık hedef! {n} puan ödülü hesabına eklendi.',
    'weekly_milestone_dialog_title': 'Haftalık hedef tamamlandı',
    'weekly_milestone_dialog_reached':
        '{n} puan eşiğine ulaştın. Kazandıkların:',
    'weekly_milestone_claim': 'Hediyeyi al',
    'weekly_chest_ready': '{n} puan sandığı — dokunarak aç',
    'weekly_milestone_coin': '+{n} coin',
    'weekly_pu_reveal': 'Açığa çıkarma',
    'weekly_pu_fifty': '%50',
    'weekly_pu_double': 'İkinci şans',
    'weekly_pu_freeze': 'Süre dondurma',
    'weekly_pu_multiplier': 'Çarpan',
    'weekly_tier_line_2000': '100 coin',
    'weekly_tier_line_4000': '200 coin · Joker×1',
    'weekly_tier_line_7000': '350 coin · Joker×1',
    'weekly_tier_line_10000': '500 coin · Joker×2',
    'practice_fill_blank_title': 'Boşluk doldurma',
    'practice_fill_blank_desc':
        'Kelimeleri gerçek İngilizce cümlelerde seçerek pekiştir.',
    'practice_fill_blank_header': 'Cümleyi tamamla',
    'practice_fill_blank_sheet_subtitle':
        'Cümleler {level} seviyesine göre seçilir — Türkçe ipucu yok; joker kullan.',
    'practice_fill_blank_level_badge': '{level}',
    'fill_blank_powerup_reveal': 'Doğru şık seçildi',
    'fill_blank_powerup_fifty': '%50 — 2 yanlış elendi',
    'fill_blank_powerup_double': 'İkinci şans hazır',
    'fill_blank_powerup_double_retry': 'İkinci şans — tekrar dene',
    'fill_blank_powerup_freeze': '+5 sn',
    'fill_blank_results_title': 'Boşluk doldurma — özet',
    'fill_blank_review': 'Özet',
    'fill_blank_given_answer': 'Verilen cevap',
    'fill_blank_wrong_answer_meaning': 'Yanlış cevap',
    'fill_blank_no_answer': 'Süre doldu / cevap seçilmedi',
    'fill_blank_review_full_en': 'Tam cümle (EN)',
    'fill_blank_review_turkish': 'Türkçe',
    'fill_blank_review_turkish_word': 'Türkçe (boşluk kelimesi)',
    'fill_blank_no_data':
        'Bu mod için soru hazırlanamadı. Uygulamayı yeniden başlatın veya bir Practice oturumu açıp tekrar deneyin.',
    'fill_blank_save_target_tooltip': 'Doğru kelimeyi Kelimelerim\'e ekle',
    'fill_blank_save_wrong_pick_tooltip': 'Seçtiğin kelimeyi Kelimelerim\'e ekle',
    'offline_banner_message': 'İnternet bağlantısı kesildi.',
    'offline_banner_practice': 'PRATİK',
    'duel_invitation_title': 'Düello Daveti!',
    'duel_invitation_message': '{username} seni düelloya davet ediyor! (Lig: {leagueCode})',
    'match_join_failed_snackbar':
        'Maça katılamadı. Maç dolmuş veya silinmiş olabilir.',
    'accept': 'Kabul Et',
    'home_showcase_practice': 'PRATİK',
    'home_showcase_duel': 'DÜELLO',
    'home_showcase_daily': 'DAILY 123',
    'level_test_progress_label': 'Seviye testi: {current} / {total}',
    'ws_practice_dialog_title': 'Practice (70/30)',
    'ws_practice_how_title': '🎯 Nasıl Oynanır?',
    'ws_practice_how_body':
        'Her oturumda 10 soru cevaplayarak kelime bilginizi pekiştirirsiniz. Sorular seviyenize göre otomatik olarak belirlenir.',
    'ws_practice_level_title': '📊 Seviye Sistemi',
    'ws_practice_level_body':
        '• A2 seviyesinden başlarsınız\n'
        '• %70+ başarı (7-10 doğru): Derhal üst seviyeye geçiş\n'
        '• %30- başarı (0-3 doğru): Derhal alt seviyeye düşüş\n'
        '• 4, 5 veya 6 doğru yaparsan aynı seviyede kalırsın.\n'
        '• Seviyeler: A1 → A2 → B1 → B2 → C1 → C2',
    'ws_practice_score_title': '💰 Puanlama',
    'ws_practice_score_body':
        '• A seviyesi: +5 / -3 puan\n'
        '• B seviyesi: +10 / -6 puan\n'
        '• C seviyesi: +15 / -9 puan\n'
        '• Hızlı cevaplar ekstra puan kazandırır!',
    'ws_duel_how_title': '🎯 Nasıl Oynanır?',
    'ws_duel_how_body':
        'Rakibinle 1v1 kelime yarışması! Bot, online rakip veya arkadaşlarınla 10 soruluk maçlarda yarış. En yüksek skoru alan kazanır!',
    'ws_duel_lp_title': '📊 LP Puanlama Sistemi',
    'ws_duel_lp_body':
        '• Standart puanlama formülü kullanılır\n'
        '• Galibiyet: +5 ile +50 puan arası\n'
        '• Mağlubiyet: -5 ile -50 puan arası\n'
        '• Beraberlik: Beklenen sonuca göre değişir\n'
        '• Güçlü rakibi yenmek: YÜKSEK kazanç (+25~+40)\n'
        '• Zayıf rakibe kaybetmek: YÜKSEK kayıp (-25~-40)',
    'ws_duel_modes_title': '🤖 Mod Seçenekleri',
    'ws_duel_modes_body':
        '• Online Rakip: Rastgele bir oyuncuyla eşleş\n'
        '• Bot: AI rakibe karşı pratik yap (LP: 1500)\n'
        '• Arkadaş: Arkadaş listenden birini davet et',
    'ws_daily_how_title': '🎯 Nasıl Oynanır?',
    'ws_daily_how_body':
        'Günde bir kez oynayabileceğin özel yarışma! A1 seviyesinden başlarsın. Doğru cevaplarsan üst seviyeye, yanlış cevaplarsan alt seviyeye geçersin.',
    'ws_daily_score_title': '📊 Puanlama Sistemi (Doğru/Yanlış)',
    'ws_daily_score_body':
        '• A1: +2 / 0 puan\n'
        '• A2: +3 / -1 puan\n'
        '• B1: +5 / -2 puan\n'
        '• B2: +7 / -3 puan\n'
        '• C1: +9 / -5 puan\n'
        '• C2: +11 / -7 puan',
    'ws_daily_important_title': '⚠️ Önemli',
    'ws_daily_important_body':
        '• Ekstra puan bonusu YOK\n• Seri puanı YOK\n• Sadece seviye puanları geçerli!',
    'ws_daily_reset_title': '⏰ Günlük Sıfırlama',
    'ws_daily_reset_body':
        'Her gün gece yarısı sıfırlanır. Yeni bir şans için yarını bekle!',
    'level_info_title': 'Seviye Bilgisi',
    'level_change_button': 'Seviyemi Değiştir',
    'level_row_a1': 'Temel kelimeler',
    'level_row_a2': 'Günlük kelimeler',
    'level_row_b1': 'Orta düzey',
    'level_row_b2': 'İleri düzey',
    'level_row_c1': 'Akademik',
    'level_row_c2': 'Uzman',
    'fill_blank_score_summary': 'Doğru: {c} / {t}',
    'correct_answer': 'Doğru kelime',
    'your_answer': 'Senin seçimin',
    'back_to_home': 'Ana sayfaya dön',
    'pack_desc_unlocked': 'Sadece bu paketteki kelimelerle çalış',
    'decline': 'Reddet',
    'my_words_info_title': 'Kelime Havuzu Bilgi',
    'my_words_info_q1': 'Kelime Havuzu Nedir?',
    'my_words_info_a1': 'Oyun sonlarında skor tablosunda yanındaki "+" butonuna basarak kaydettiğiniz tüm kelimeler bu alanda toplanır.',
    'my_words_info_q2': 'Nasıl Çalışılır?',
    'my_words_info_a2': 'Bu kısma girerek kendi oluşturduğunuz kelime listesini görebilir ve "Test Yourself" butonu ile flashcard modunda pratik yapabilirsiniz.',
    'failed_to_join': 'Maça katılamadım (Hata veya iptal)',
    'premium_required_title': '👑 Premium Gerekli',
    'premium_required_body': 'Bu özellik sadece Premium üyelere özeldir!',
    'premium_benefits': 'Premium Avantajları:',
    'benefit_maxigame': '✓ 3-4 kişilik MaxiGame',
    'benefit_friends': '✓ Arkadaş odası oluşturma',
    'benefit_cosmetics': '✓ Özel avatarlar ve çerçeveler',
    'benefit_ads': '✓ Reklamsız deneyim',
    'later': 'Daha Sonra',
    'daily_played_today': 'Bugünkü yarışmayı tamamladınız!',
    'view_results': 'Sonuçları Gör',
    'watch_ad_replay': 'Reklam İzle & Tekrar Oyna',
    'loading_ad': 'Reklam Yükleniyor...',
    'ad_failed': 'Reklam yüklenemedi, lütfen tekrar deneyin.',
    'info_level_determination': 'Seviye Belirleme',
    'info_level_determination_body': 'İlk 3 oturum boyunca vereceğiniz cevaplar başlangıç seviyenizi belirler. Bu aşamada her oturum sonunda seviyeniz anlık olarak güncellenebilir.',
    'info_test_content': 'Test İçeriği',
    'info_test_content_body': '• Toplam 3 oturum (Her biri 10 soru)\n• Sorular A1\'den C1\'e kadar dinamik olarak değişir.\n• 3 oturum sonunda belirlenen seviyenizle ELITE LİG\'e dahil olursunuz.',
    'info_duel_unlocked': 'Duel Modu',
    'info_duel_unlocked_body': '• 3 oturumu tamamladığınızda Duel modu açılır.\n• Arkadaşlarınıza meydan okuyabilir ve ödüller kazanabilirsiniz!',
    'let_start': 'Başlayalım!',
    'select_category': 'Çalışma Kategorisi Seç',
    'select_category_desc': 'Birden fazla paket seçebilirsin. Seçilen paketlerden karışık sorular gelir.',
    'special_packs': 'Özel Paketler',
    'profile_view': 'Profil Görünümü',
    'promo_code_title': 'Promosyon Kodu',
    'promo_code_body': 'Premium kazanmak için promosyon kodunuzu girin:',
    'enter_code': 'Kodu girin...',
    'game_guide': 'Oyun Rehberi',
    'guide_title_1': 'LUGORENA Nedir?',
    'guide_desc_1': 'İngilizce kelime bilgini test et ve geliştir! Farklı oyun modlarıyla eğlenerek öğren.',
    'guide_title_2': 'Duel Modu',
    'guide_desc_2': 'Online rakiplerinle, arkadaşlarınla veya seviyene uygun botla 10 soruluk düellolara katıl!',
    'guide_title_3': 'Daily 123',
    'guide_desc_3': '123 saniyede 123 puana ulaşmaya çalış! Her gün yeni bir meydan okuma seni bekliyor. Hızlı ol, üst sıraları yakala!',
    'guide_title_4': 'Practice',
    'guide_desc_4': 'Kendi hızında pratik yap. A2 seviyesinden başla, başarına göre seviye atla!',
    'guide_title_5': 'Premium Özellikler',
    'guide_desc_5': 'Premium üyelikle reklamsız deneyim, özel temalar, sınırsız duel ve daha fazlası!',
    'question': 'Soru',
    'session': 'Oturum',
    'seconds_short': 'sn',
    'level': 'Seviye',
    'continue_button': 'Devam Et',
    'correct_message': 'DOĞRU!',
    'wrong_message': 'YANLIŞ!',
    'level_test_title': 'Seviye Tespiti',
    'level_test_complete': 'Seviye Tespiti Tamamlandı!',
    'determined_level': 'Belirlenen Seviye',
    'starting_lp': 'Başlangıç LP:',
    'duel_unlocked_desc': 'Artık Düello modunda diğer oyunculara karşı yarışabilirsin!',
    'success_rate': 'Başarı Oranı',
    'great': 'Harika!',
    'good': 'İyi!',
    'keep_working': 'Çalışmaya Devam!',
    'one_session_left': 'Son oturum kaldı! (2/3) Düello modu açılacak.',
    'sessions_remaining': 'Son {remaining} oturum kaldı! ({progress}/3) Düello modu açılacak.',
    'towards_duel': 'Düello Moduna Doğru!',
    'get_ready': 'Hazır Ol!',
    'hide_words': 'Kelimeleri Gizle',
    'show_words': 'Kelimeleri Göster',
    'words_appeared': 'Çıkan Kelimeler',
    'words_history': 'ÇIKMIŞ KELİMELER',
    'level_up_message': 'Seviye Atladın!',
    'level_down_message': 'Seviye Düştü',
    'new_level_prefix': 'Yeni Seviye:',
    'select_all': 'Tümünü Seç',
    'deselect_all': 'Tümünü Kaldır',
    'select_level': 'Seviyeni Seç',
    'select_level_desc': 'İngilizce seviyeni en iyi sen bilirsin!',
    'start_with': 'ile Başla',
    'please_select_level': 'Seviye Seçin',
    'save_selected': 'Seçilenleri Kaydet',
    'words_saved_message': '{count} kelime kayıt edildi',
    'duel_unlocked_dialog_title': 'Düello Modu Açıldı!',
    'duel_unlocked_dialog_body': 'Artık arkadaşlarına veya bota karşı yarışabilirsin!',
    'awesome': 'Harika!',
    'ongoing_games': 'Devam Eden Oyunlar',
    'no_ongoing_games': 'Devam eden oyun yok',
    'select_level_find_opponent': 'Seviye seç ve rakibini bul!',
    'find_opponent_button': 'Rakip Bul',
    'bot_button': 'Bot',
    'bot_ready_message': 'Yapay zeka rakibin hazır! Bakalım kim daha hızlı?',
    'waiting_for_friend': '{username} daveti kabul etsin diye bekliyorum...',
    'searching_optimal_opponent': 'Harika bir rakip bulmak için sözlükleri tarıyorum!',
    'searching_opponent': 'RAKİP ARANIYOR',
    'match_starting': 'Maç başlıyor...',
    'league_prefix': 'LİG:',
    'level_a1_desc': 'Temel kelimeler: hello, book, water, eat...',
    'level_a2_desc': 'Günlük kelimeler: government, customer, agree...',
    'level_b1_desc': 'Orta seviye: establish, distinguish, crucial...',
    'level_b2_desc': 'İleri seviye: undermine, coherent, mitigate...',
    'level_c1_desc': 'Akademik: discern, pervasive, corroborate...',
    'level_c2_desc': 'Uzman: enigmatic, inexorably, jurisprudence...',
    'total_points': 'Toplam Puan',
    'daily_streak': 'Günlük Seri',
    'wins': 'Galibiyet',
    'losses': 'Mağlubiyet',
    'total_played': 'Toplam {count} Maç Oynandı',
    'joining_date': '{date} tarihinde katıldı',
    'joining_date_unknown': 'Kayıt tarihi bilinmiyor',
    'weekly_activity': 'Haftalık Aktivite',
    'mon': 'Pzt',
    'tue': 'Sal',
    'wed': 'Çar',
    'thu': 'Per',
    'fri': 'Cum',
    'sat': 'Cmt',
    'sun': 'Paz',
    'duel_performance': 'DÜELLO PERFORMANSI',
    'level_short': 'DÜZEY',
    'time_short': 'SÜRE',
    'points_short': 'PUAN',
    'days_unit': 'Gün',
    'lp_points': 'LP Puanı',
    'daily_quests_title': 'GÜNLÜK GÖREVLER',
    'home_quest_pill': 'Görevler',
    'welcome_gift_title': 'Hoşgeldin Hediyesi!',
    'welcome_gift_body': 'LUGORENA\'ya hoşgeldin! 🎉\n\n💰 200 Altın\n🃏 Tüm jokerlerden 2\'şer adet\n\nHediyeleriniz hesabınıza eklendi!',
    'great_btn': 'Harika!',
    'daily_bonus_streak': '{streak} Gün Serisi!',
    'coins_added': '+{coins} Altın 🪙',
    'continue_btn': 'Devam',
    'daily_results': 'Günün Sonuçları',
    'main_menu': 'Ana Menüye Dön',
    'career_stats': 'Kariyer İstatistikleri',
    'game_count': 'Oyun Sayısı',
    'win_rate': 'Kazanma Oranı',
    'league_score': 'Lig Puanı',
    'matches': 'Maçlar',
    'opponent_profile': 'RAKİP PROFİLİ',
    'mutual_score': 'KARŞILIKLI SKOR',
    'opponent_stats_title': 'RAKİP İSTATİSTİKLERİ',
    'current_streak': 'Güncel Seri',
    'highest_streak': 'En Yüksek Seri',
    'daily_competition': 'GÜNLÜK YARIŞMA',
    'global_ranking': 'GENEL SIRALAMA',
    'rank_label': 'Sıralama',
    'total_players': 'Toplam Oyuncu',
    'avg_points': 'Ortalama Puan',
    'correct_answers': 'Doğru Cevaplar',
    'wrong_answers': 'Yanlış Cevaplar',
    'no_correct_yet': 'Henüz doğru cevap yok',
    'no_wrong_yet': 'Hiç yanlış cevap yok! 🎉',
    'added_to_my_words': '{count} kelime "Kelimelerim"e eklendi',
    'removed_from_my_words': '{count} kelime "Kelimelerim"den çıkarıldı',
    'add_label': 'Ekle',
    'remove_label': 'Çıkar',
    'time_up': 'SÜRE DOLDU :(',
    'congrats': 'TEBRİKLER!',
    'see_you_tomorrow': 'Yarın Tekrar Görüşmek Üzere',
    'calculating': 'Hesaplanıyor...',
    'practice_stats': 'Practice',
    'word_count_label': '{count} kelime',
    'win_title': 'KAZANDIN!',
    'lose_title': 'KAYBETTİN',
    'draw_title': 'BERABERE',
    'winner': 'KAZANAN',
    'you': 'Sen',
    'opponent_name': 'Rakip',
    'add_selected_to_pool': 'Seçilenleri My Words\'e Ekle',
    'words_added_to_my_words': 'kelime "Kelimelerim"e eklendi',
    'play_again': 'Tekrar Oyna',
    'rematch_button': 'Rövanş Yap',
    'invite_sent': 'Rövanş daveti gönderildi! Bekleniyor...',
    'invite_failed': 'Davet gönderilemedi.',
    'watch_ad': 'Reklam İzle',
    'replay': 'Tekrar Oyna',
    'premium_ending_warning': 'Premium üyeliğiniz {days} gün içinde sona eriyor.',
    'welcome_jokers_added': '🎁 Her Jokerden 2 Adet Eklendi!',
    'correct': 'Doğru',
    'wrong': 'Yanlış',
    'lp_progress': 'LP İlerlemesi',
    'quit_practice_title': 'Antrenmanı Kapat',
    'quit_practice_confirm': 'Şu anki ilerlemen kaydedilmeyecek. Çıkmak istediğine emin misin?',
    'confirm_quit': 'Evet, Çık',
  };

  static const Map<String, String> _enStrings = {
    'settings': 'Settings',
    'general': 'General',
    'language': 'Language / Dil',
    'sound_vibration': 'Sound & Vibration',
    'sound': 'Sound',
    'sound_subtitle': 'Toggle game sounds',
    'vibration': 'Vibration',
    'vibration_subtitle': 'In-game vibration feedback',
    'notifications': 'Notifications',
    'notifications_subtitle': 'Toggle push notifications',
    'legal': 'Legal',
    'terms': 'Terms of Service',
    'privacy': 'Privacy Policy',
    'other': 'Other',
    'support': 'Support',
    'support_subtitle': 'Help and feedback',
    'guide': 'Guide',
    'replay_tutorial': 'Replay Tutorial',
    'promo_code': 'Use Promo Code',
    'logout': 'Logout',
    'delete_account': 'Delete Account',
    'version': 'Version',
    'cancel': 'Cancel',
    'apply': 'Apply',
    'quit_duel_title': 'About to Surrender!',
    'quit_duel_confirm': 'If you quit the duel, you will be considered defeated and lose points. Are you sure you want to quit?',
    'confirm': 'Accept Defeat',
    'confirm_logout': 'Are you sure you want to log out?',
    'confirm_delete': 'Are you sure you want to delete your account and all data permanently? This action cannot be undone.',
    'practice_mode': 'Practice',
    'daily_123': 'Daily 123',
    'achievements': 'Achievements',
    'profile': 'Profile',
    'shop': 'Shop',
    'stats': 'Statistics',
    'leaderboard': 'Leaderboard',
    'practice_info': 'Practice based on your level',
    'duel_info': 'Duel with your friends',
    'play': 'Play',
    'start': 'Start',
    'next': 'Next',
    'skip': 'Skip',
    'back': 'Back',
    'level_test': 'LEVEL TEST',
    'intro_skip': 'Skip',
    'continue_practice': 'Continue Practice',
    'duel_locked_message': 'Complete 3 Practice sessions to unlock Duel mode.',
    'daily_123_subtitle': 'Compete to break the record',
    'my_words': 'My Words',
    'home': 'Home',
    'ranking': 'Ranking',
    'premium_feature': 'Premium Feature',
    'premium_info': 'Uploading a profile photo is a Premium feature.',
    'language_passport_title': 'Language Passport',
    'language_passport_subtitle': 'Your learning map and specialties',
    'close': 'Close',
    'go_premium': 'Go Premium',
    'profile_updated': 'Profile photo updated successfully! ✨',
    'upload_failed': 'Upload failed.',
    'statistics': 'Statistics',
    'awards': 'Awards',
    'change_appearance': 'Change Appearance',
    'upload_profile_photo': 'Upload Profile Photo',
    'only_premium': 'Exclusive to Premium members',
    'purchased_avatars': 'Purchased Avatars',
    'no_avatars': 'No avatars purchased yet',
    'go_to_market': 'Go to Market',
    'frames': 'Frames',
    'no_frames': 'No frames purchased yet',
    'none': 'None',
    'friends': 'Friends',
    'completed': 'Completed',
    'profile_title': 'Profile',
    'stats_and_settings': 'Stats & Settings',
    'info_how_to_play': '🎯 How to Play?',
    'info_practice_body': 'Practice your vocabulary by answering 10 questions per session. Questions are automatically selected based on your level.',
    'info_level_system': '📊 Level System',
    'info_level_system_body': '• 70%+ success in 2 sessions: Level Up\n• 30%- success in 2 sessions: Level Down\n• Levels: A1 → A2 → B1 → B2 → C1 → C2',
    'info_scoring': '💰 Scoring',
    'info_scoring_body': '• A: +5 / -3 | B: +10 / -6 | C: +15 / -9\n• Fast answers earn bonus points!',
    'info_got_it': 'Got it!',
    'info_duel_title': 'Duel Mode',
    'info_duel_body': '1v1 vocabulary competition! Compete with bots, online opponents, or friends in 10-question matches. Highest score wins!',
    'info_lp_system': '📊 LP Scoring System',
    'info_lp_system_body': '• Win: +5 to +50 LP\n• Loss: -5 to -50 LP\n• Defeating stronger opponents earns more points.',
    'info_modes': '🤖 Game Modes',
    'info_modes_body': '• Online: Match with a random player\n• Bot: Practice against AI\n• Friend: Invite someone from your list',
    'info_daily_title': 'Daily 123',
    'info_daily_body': 'Special daily competition! Start from A1 and climb higher with each correct answer.',
    'info_daily_scoring': '📊 Scoring',
    'info_daily_scoring_body': 'Only level points apply. No streak or speed bonuses.',
    'info_dynamic_level': 'Dynamic Level System',
    'info_dynamic_level_body': 'Level up with each correct answer, level down with each wrong one. Harder questions give more points!',
    'info_scoring_table': 'Scoring Table',
    'info_important': '⚠️ Important',
    'info_important_body': 'Resets every day at midnight.',
    'league_a': 'League A',
    'league_b': 'League B',
    'league_c': 'League C',
    'your_rank': 'Your Rank',
    'your_rank_in': 'Your Rank ({category}):',
    'leaderboard_rank_score_label': 'Rank points',
    'leaderboard_row_secondary_hint': 'Stats (not rank points)',
    'leaderboard_badge_wins': 'Wins',
    'leaderboard_badge_course': 'Course level',
    'no_data_yet': 'No data yet',
    'search_username': 'Search by username...',
    'search_min_chars': 'Enter at least 3 characters',
    'user_not_found': 'User not found',
    'global': 'Global',
    'powerups': 'Powerups',
    'packs': 'Packs',
    'customize': 'Customize',
    'coins': 'Coins',
    'premium': 'Premium',
    'market': 'Market',
    'buy': 'Buy',
    'owned': 'Owned',
    'equipped': 'Equipped',
    'select': 'Select',
    'resume_game': 'RESUME GAME',
    'resume_duel': 'RESUME DUEL',
    'select_duel_mode': 'Select Duel Mode',
    'how_to_compete': 'How would you like to compete?',
    'lugo_duel_title': 'LUGO DUEL',
    'lugo_duel_desc': 'Compete with online players (Affects LP)',
    'bot_duel_title': 'BOT DUEL',
    'bot_duel_desc': 'Compete against a bot at your level',
    'friend_duel_title': 'FRIEND DUEL',
    'friend_duel_desc': 'Invite someone from your friends list',
    'start_practice_btn': 'Start Practice',
    'weekly_practice_bar_title': 'Weekly Practice Points',
    'weekly_practice_milestone_snack':
        'Weekly milestone! Rewards for {n} points added to your account.',
    'weekly_milestone_dialog_title': 'Weekly milestone complete',
    'weekly_milestone_dialog_reached':
        'You reached the {n} point tier. You earned:',
    'weekly_milestone_claim': 'Claim reward',
    'weekly_chest_ready': '{n}-pt chest — tap to open',
    'weekly_milestone_coin': '+{n} coins',
    'weekly_pu_reveal': 'Reveal',
    'weekly_pu_fifty': '50/50',
    'weekly_pu_double': 'Second chance',
    'weekly_pu_freeze': 'Freeze time',
    'weekly_pu_multiplier': 'Multiplier',
    'weekly_tier_line_2000': '100 coins',
    'weekly_tier_line_4000': '200 coins · Joker×1',
    'weekly_tier_line_7000': '350 coins · Joker×1',
    'weekly_tier_line_10000': '500 coins · Joker×2',
    'practice_fill_blank_title': 'Fill in the blank',
    'practice_fill_blank_desc':
        'Reinforce words by choosing them in real English sentences.',
    'practice_fill_blank_header': 'Complete the sentence',
    'practice_fill_blank_sheet_subtitle':
        'Sentences match level {level} — no Turkish hint; use power-ups.',
    'practice_fill_blank_level_badge': '{level}',
    'fill_blank_powerup_reveal': 'Correct option selected',
    'fill_blank_powerup_fifty': '50/50 — 2 wrong options removed',
    'fill_blank_powerup_double': 'Second chance ready',
    'fill_blank_powerup_double_retry': 'Second chance — try again',
    'fill_blank_powerup_freeze': '+5 sec',
    'fill_blank_results_title': 'Fill in the blank — summary',
    'fill_blank_review': 'Review',
    'fill_blank_given_answer': 'Your answer',
    'fill_blank_wrong_answer_meaning': 'Wrong answer',
    'fill_blank_no_answer': 'Time up / no answer selected',
    'fill_blank_review_full_en': 'Full sentence (EN)',
    'fill_blank_review_turkish': 'Turkish',
    'fill_blank_review_turkish_word': 'Turkish (blank word)',
    'fill_blank_no_data':
        'Could not prepare questions for this mode. Restart the app or open a Practice session and try again.',
    'fill_blank_save_target_tooltip': 'Add correct word to My Words',
    'fill_blank_save_wrong_pick_tooltip': 'Add your pick to My Words',
    'offline_banner_message': 'No internet connection.',
    'offline_banner_practice': 'PRACTICE',
    'duel_invitation_message':
        '{username} invited you to a duel! (League: {leagueCode})',
    'match_join_failed_snackbar':
        'Could not join the match. It may be full or removed.',
    'home_showcase_practice': 'PRACTICE',
    'home_showcase_duel': 'DUEL',
    'home_showcase_daily': 'DAILY 123',
    'level_test_progress_label': 'Level test: {current} / {total}',
    'ws_practice_dialog_title': 'Practice (70/30)',
    'ws_practice_how_title': '🎯 How to play?',
    'ws_practice_how_body':
        'Answer 10 questions per session to strengthen your vocabulary. Questions are chosen automatically for your level.',
    'ws_practice_level_title': '📊 Level system',
    'ws_practice_level_body':
        '• You start at A2\n'
        '• 70%+ score (7–10 correct): Move up immediately\n'
        '• 30%- score (0–3 correct): Move down immediately\n'
        '• 4, 5, or 6 correct: stay on the same level\n'
        '• Levels: A1 → A2 → B1 → B2 → C1 → C2',
    'ws_practice_score_title': '💰 Scoring',
    'ws_practice_score_body':
        '• Level A: +5 / -3\n'
        '• Level B: +10 / -6\n'
        '• Level C: +15 / -9\n'
        '• Fast answers earn bonus points!',
    'ws_duel_how_title': '🎯 How to play?',
    'ws_duel_how_body':
        '1v1 vocabulary race! Compete in 10-question matches against a bot, online opponent, or friends. Highest score wins!',
    'ws_duel_lp_title': '📊 LP scoring',
    'ws_duel_lp_body':
        '• Standard LP formula\n'
        '• Win: +5 to +50 LP\n'
        '• Loss: -5 to -50 LP\n'
        '• Draw: depends on expected outcome\n'
        '• Beating a stronger opponent: HIGH gain (+25~+40)\n'
        '• Losing to a weaker opponent: HIGH loss (-25~-40)',
    'ws_duel_modes_title': '🤖 Modes',
    'ws_duel_modes_body':
        '• Online: match with a random player\n'
        '• Bot: practice vs AI (LP: 1500)\n'
        '• Friend: invite from your friends list',
    'ws_daily_how_title': '🎯 How to play?',
    'ws_daily_how_body':
        'A special daily challenge! Start at A1. Correct answers move you up a level; wrong answers move you down.',
    'ws_daily_score_title': '📊 Scoring (correct / wrong)',
    'ws_daily_score_body':
        '• A1: +2 / 0\n'
        '• A2: +3 / -1\n'
        '• B1: +5 / -2\n'
        '• B2: +7 / -3\n'
        '• C1: +9 / -5\n'
        '• C2: +11 / -7',
    'ws_daily_important_title': '⚠️ Important',
    'ws_daily_important_body':
        '• No extra bonuses\n• No streak points\n• Only level points count!',
    'ws_daily_reset_title': '⏰ Daily reset',
    'ws_daily_reset_body':
        'Resets at midnight every day. Come back tomorrow for a new run!',
    'level_info_title': 'Level info',
    'level_change_button': 'Change my level',
    'level_row_a1': 'Basic vocabulary',
    'level_row_a2': 'Everyday words',
    'level_row_b1': 'Intermediate',
    'level_row_b2': 'Advanced',
    'level_row_c1': 'Academic',
    'level_row_c2': 'Expert',
    'fill_blank_score_summary': 'Correct: {c} / {t}',
    'correct_answer': 'Correct word',
    'your_answer': 'Your choice',
    'back_to_home': 'Back to home',
    'pack_desc_unlocked': 'Practice only with words from this pack',
    'pack_desc_locked': 'Buy from store to unlock this pack',
    'duel_invitation_title': 'Duel Invitation!',
    'duel_invitation_body': 'invited you to a duel!',
    'duel_invitation_league': 'League',
    'accept': 'Accept',
    'decline': 'Decline',
    'my_words_info_title': 'Word Pool Info',
    'my_words_info_q1': 'What is Word Pool?',
    'my_words_info_a1': 'All words you save by clicking the "+" button on the score table at the end of games are collected here.',
    'my_words_info_q2': 'How to Practice?',
    'my_words_info_a2': 'In this section, you can view your personal word list and practice using the "Test Yourself" button in flashcard mode.',
    'failed_to_join': 'Could not join (Error or cancelled)',
    'premium_required_title': '👑 Premium Required',
    'premium_required_body': 'This feature is exclusive to Premium members!',
    'premium_benefits': 'Premium Benefits:',
    'benefit_maxigame': '✓ 3-4 player MaxiGame',
    'benefit_friends': '✓ Create friend rooms',
    'benefit_cosmetics': '✓ Custom avatars and frames',
    'benefit_ads': '✓ Ad-free experience',
    'later': 'Later',
    'daily_played_today': 'You have completed today\'s challenge!',
    'view_results': 'View Results',
    'watch_ad_replay': 'Watch Ad & Replay',
    'loading_ad': 'Loading Ad...',
    'ad_failed': 'Failed to load ad, please try again.',
    'info_level_determination': 'Level Determination',
    'info_level_determination_body': 'Your answers during the first 3 sessions determine your starting level. At this stage, your level can be updated instantly after each session.',
    'info_test_content': 'Test Content',
    'info_test_content_body': '• Total 3 sessions (10 questions each)\n• Questions change dynamically from A1 to C1.\n• After 3 sessions, you will join the ELITE LEAGUE with your determined level.',
    'info_duel_unlocked': 'Duel Mode',
    'info_duel_unlocked_body': '• Duel mode unlocks when you complete 3 sessions.\n• You can challenge your friends and win rewards!',
    'let_start': 'Let\'s Start!',
    'select_category': 'Select Practice Category',
    'select_category_desc': 'You can select multiple packs. Questions will be mixed from selected packs.',
    'special_packs': 'Special Packs',
    'profile_view': 'Profile View',
    'promo_code_title': 'Promo Code',
    'promo_code_body': 'Enter your promo code to get Premium:',
    'enter_code': 'Enter code...',
    'game_guide': 'Game Guide',
    'guide_title_1': 'What is LUGORENA?',
    'guide_desc_1': 'Test and improve your English vocabulary! Learn while having fun with different game modes.',
    'guide_title_2': 'Duel Mode',
    'guide_desc_2': 'Join 10-question duels with online opponents, friends, or a bot at your level!',
    'guide_title_3': 'Daily 123',
    'guide_desc_3': 'Try to reach 123 points in 123 seconds! A new challenge awaits you every day. Be fast, reach the top!',
    'guide_title_4': 'Practice',
    'guide_desc_4': 'Practice at your own pace. Start from level A2 and level up based on your success!',
    'guide_title_5': 'Premium Features',
    'guide_desc_5': 'Ad-free experience with Premium membership, special themes, unlimited duels and more!',
    'question': 'Question',
    'session': 'Session',
    'seconds_short': 's',
    'level': 'Level',
    'continue_button': 'Continue',
    'correct_message': 'CORRECT!',
    'wrong_message': 'WRONG!',
    'level_test_title': 'Level Test',
    'level_test_complete': 'Level Test Completed!',
    'determined_level': 'Determined Level',
    'starting_lp': 'Starting LP:',
    'duel_unlocked_desc': 'Now you can compete against other players in Duel mode!',
    'success_rate': 'Success Rate',
    'great': 'Great!',
    'good': 'Good!',
    'keep_working': 'Keep Working!',
    'one_session_left': 'One session left! (2/3) Duel mode will unlock.',
    'sessions_remaining': '{remaining} sessions left! ({progress}/3) Duel mode will unlock.',
    'towards_duel': 'Towards Duel Mode!',
    'get_ready': 'Get Ready!',
    'hide_words': 'Hide Words',
    'show_words': 'Show Words',
    'words_appeared': 'Words that Appeared',
    'words_history': 'WORD HISTORY',
    'level_up_message': 'Level Up!',
    'level_down_message': 'Level Down',
    'new_level_prefix': 'New Level:',
    'select_all': 'Select All',
    'deselect_all': 'Deselect All',
    'select_level': 'Select Your Level',
    'select_level_desc': 'You know your English level best!',
    'start_with': 'Start with',
    'please_select_level': 'Please Select a Level',
    'save_selected': 'Save Selected',
    'words_saved_message': '{count} words saved',
    'duel_unlocked_dialog_title': 'Duel Mode Unlocked!',
    'duel_unlocked_dialog_body': 'You can now compete against friends or bots!',
    'awesome': 'Awesome!',
    'ongoing_games': 'Ongoing Games',
    'no_ongoing_games': 'No ongoing games',
    'select_level_find_opponent': 'Select level and find opponent!',
    'find_opponent_button': 'Find Opponent',
    'bot_button': 'Bot',
    'bot_ready_message': 'Your AI opponent is ready! Let\'s see who is faster?',
    'waiting_for_friend': 'Waiting for {username} to accept the invitation...',
    'searching_optimal_opponent': 'Searching for a great opponent!',
    'searching_opponent': 'SEARCHING OPPONENT',
    'match_starting': 'Match starting...',
    'league_prefix': 'LEAGUE:',
    'level_a1_desc': 'Basic words: hello, book, water, eat...',
    'level_a2_desc': 'Daily words: government, customer, agree...',
    'level_b1_desc': 'Intermediate level: establish, distinguish, crucial...',
    'level_b2_desc': 'Advanced level: undermine, coherent, mitigate...',
    'level_c1_desc': 'Academic: discern, pervasive, corroborate...',
    'level_c2_desc': 'Expert: enigmatic, inexorably, jurisprudence...',
    'total_points': 'Total Points',
    'daily_streak': 'Daily Streak',
    'wins': 'Wins',
    'losses': 'Losses',
    'lp_progress': 'LP Progress',
    'total_played': 'Total {count} Matches Played',
    'joining_date': 'Joined on {date}',
    'joining_date_unknown': 'Join date unknown',
    'weekly_activity': 'Weekly Activity',
    'mon': 'Mon',
    'tue': 'Tue',
    'wed': 'Wed',
    'thu': 'Thu',
    'fri': 'Fri',
    'sat': 'Sat',
    'sun': 'Sun',
    'duel_performance': 'DUEL PERFORMANCE',
    'level_short': 'LEVEL',
    'time_short': 'TIME',
    'points_short': 'POINTS',
    'days_unit': 'Days',
    'lp_points': 'LP Rating',
    'daily_results': 'Today\'s Results',
    'main_menu': 'Return to Main Menu',
    'career_stats': 'Career Statistics',
    'game_count': 'Game Count',
    'win_rate': 'Win Rate',
    'league_score': 'League Score',
    'matches': 'Matches',
    'opponent_profile': 'OPPONENT PROFILE',
    'mutual_score': 'MUTUAL SCORE',
    'opponent_stats_title': 'OPPONENT STATISTICS',
    'current_streak': 'Current Streak',
    'highest_streak': 'Highest Streak',
    'daily_competition': 'DAILY COMPETITION',
    'global_ranking': 'GLOBAL RANKING',
    'rank_label': 'Rank',
    'total_players': 'Total Players',
    'avg_points': 'Avg Points',
    'correct_answers': 'Correct Answers',
    'wrong_answers': 'Wrong Answers',
    'no_correct_yet': 'No correct answers yet',
    'no_wrong_yet': 'No wrong answers! 🎉',
    'added_to_my_words': '{count} words added to "My Words"',
    'removed_from_my_words': '{count} words removed from "My Words"',
    'add_label': 'Add',
    'remove_label': 'Remove',
    'time_up': 'TIME IS UP :(',
    'congrats': 'CONGRATS!',
    'see_you_tomorrow': 'See You Again Tomorrow',
    'calculating': 'Calculating...',
    'practice_stats': 'Practice',
    'word_count_label': '{count} words',
    'points': 'Points',
    'duel_unlock_progress': 'Complete 3 Sessions to Unlock Duel',
    'keep_practicing': 'Keep Practicing Based on Your Level',
    'duel_desc': 'Compete against friends or a bot',
    'duel_remaining': 'Only {kalan} sessions remaining!',
    'level_test_desc': 'Complete 3 sessions to determine your starting level',
    'duel_mode': 'Duel Mode',
    'buddy_duel_title': 'BUDDY DUEL',
    'buddy_duel_desc': 'Compete with friends (Affects LP)',
    'daily_quests_title': 'DAILY QUESTS',
    'home_quest_pill': 'Quests',
    'welcome_gift_title': 'Welcome Gift!',
    'welcome_title': 'Welcome',
    'daily_bonus_ready': 'DAILY BONUS IS READY',
    'claim_rewards': 'CLAIM REWARDS!',
    'coins_unit_label': 'Coins',
    'new_reward': 'NEW REWARD!',
    'next_reward': 'Next Reward →',
    'great_confetti': 'Great! 🎊',
    'daily_login_rewards': 'Daily Login Rewards',
    'streak_message': 'You\'ve been here for {streak} days straight!',
    'grand_prize': 'Grand Prize',
    'day_label': 'Day',
    'ad_failed_or_skipped': 'Ad failed to load or was skipped.',
    'your_answer_short': 'Your',
    'saved': 'Saved',
    'word_selected_count': '{count} words selected',
    'welcome_gift_body': 'Welcome to LUGORENA! 🎉\n\n💰 200 Coins\n🃏 2 of each Joker\n\nYour gifts have been added to your account!',
    'great_btn': 'Great!',
    'daily_bonus_streak': '{streak} Day Streak!',
    'coins_added': '+{coins} Coins 🪙',
    'continue_btn': 'Continue',
    'win_title': 'YOU WON!',
    'lose_title': 'YOU LOST',
    'draw_title': 'IT\'S A DRAW',
    'winner': 'WINNER',
    'you': 'You',
    'opponent_name': 'Opponent',
    'add_selected_to_pool': 'Add Selected to My Words',
    'words_added_to_my_words': 'words added to My Words',
    'play_again': 'Play Again',
    'rematch_button': 'Rematch',
    'invite_sent': 'Rematch invite sent! Waiting...',
    'invite_failed': 'Invite failed.',
    'watch_ad': 'Watch Ad',
    'replay': 'Replay',
    'premium_ending_warning': 'Your premium membership ends in {days} days.',
    'welcome_jokers_added': '🎁 2 of Each Joker Added!',
    'correct': 'Correct',
    'wrong': 'Wrong',
    'quit_practice_title': 'Quit Practice',
    'quit_practice_confirm': 'Your current progress will not be saved. Are you sure you want to quit?',
    'confirm_quit': 'Yes, Quit',
  };
}
