enum CosmeticType { frame, title, avatar, animation, emote }

class CosmeticItem {
  final String id;
  final String name;
  final String description;
  final CosmeticType type;
  final int price;
  final String previewValue; // Emoji, icon name, or color code
  final bool isPremiumOnly;
  final int borderWidth; // Frame için kenar kalınlığı (3-6 arası)

  const CosmeticItem({
    required this.id,
    required this.name,
    required this.description,
    required this.type,
    required this.price,
    required this.previewValue,
    this.isPremiumOnly = false,
    this.borderWidth = 4,
  });

  static const List<CosmeticItem> availableItems = [
    // ===== ÇERÇEVELER (Kalın ve Neon tarzı) =====
    CosmeticItem(
      id: 'frame_gold',
      name: 'Altın Çerçeve',
      description: 'Profiline asalet katar',
      type: CosmeticType.frame,
      price: 200,
      previewValue: 'ffd700', // Hex color
      borderWidth: 5,
    ),
    CosmeticItem(
      id: 'frame_neon',
      name: 'Neon Mavi',
      description: 'Gelecekten gelen stil',
      type: CosmeticType.frame,
      price: 350,
      previewValue: '00f2ff',
      borderWidth: 5,
    ),
    CosmeticItem(
      id: 'frame_neon_pink',
      name: 'Neon Pembe',
      description: 'Parlak ve enerjik',
      type: CosmeticType.frame,
      price: 350,
      previewValue: 'ff00ff',
      borderWidth: 5,
    ),
    CosmeticItem(
      id: 'frame_neon_green',
      name: 'Neon Yeşil',
      description: 'Matrix vibes',
      type: CosmeticType.frame,
      price: 350,
      previewValue: '00ff00',
      borderWidth: 5,
    ),
    CosmeticItem(
      id: 'frame_rainbow',
      name: 'Gökkuşağı',
      description: 'Tüm renkler bir arada',
      type: CosmeticType.frame,
      price: 600,
      previewValue: 'gradient',
      borderWidth: 6,
      isPremiumOnly: true,
    ),
    CosmeticItem(
      id: 'frame_fire',
      name: 'Ateş Çerçeve',
      description: 'Alevler içinde parla',
      type: CosmeticType.frame,
      price: 500,
      previewValue: 'ff4500',
      borderWidth: 6,
    ),
    CosmeticItem(
      id: 'frame_ice',
      name: 'Buz Çerçeve',
      description: 'Soğuk ama şık',
      type: CosmeticType.frame,
      price: 400,
      previewValue: 'add8e6',
      borderWidth: 5,
    ),

    // ===== UNVANLAR =====
    CosmeticItem(
      id: 'title_legend',
      name: 'Efsane',
      description: 'Sadece en iyiler için',
      type: CosmeticType.title,
      price: 500,
      previewValue: 'Efsane',
      isPremiumOnly: true,
    ),
    CosmeticItem(
      id: 'title_rookie',
      name: 'Çaylak',
      description: 'Yeni başlayanların dostu',
      type: CosmeticType.title,
      price: 50,
      previewValue: 'Çaylak',
    ),
    CosmeticItem(
      id: 'title_master',
      name: 'Usta',
      description: 'Kelime ustası',
      type: CosmeticType.title,
      price: 300,
      previewValue: 'Usta',
    ),
    CosmeticItem(
      id: 'title_champion',
      name: 'Şampiyon',
      description: 'Düello şampiyonu',
      type: CosmeticType.title,
      price: 400,
      previewValue: 'Şampiyon',
    ),

    // ===== LUGO VE RENA (Özel Karakterler) — görseller assets/images/avatars/ altında =====
    CosmeticItem(
      id: 'avatar_lugo_klasik',
      name: 'Bilge Lugo',
      description: '',
      type: CosmeticType.avatar,
      price: 500,
      previewValue: 'assets/images/avatars/avatar_scholar_blue.png',
    ),
    CosmeticItem(
      id: 'avatar_gezgin',
      name: 'Gezgin',
      description: '',
      type: CosmeticType.avatar,
      price: 500,
      previewValue: 'assets/images/avatars/avatar_gezgin.png',
    ),
    CosmeticItem(
      id: 'avatar_hekim',
      name: 'Hekim',
      description: '',
      type: CosmeticType.avatar,
      price: 500,
      previewValue: 'assets/images/avatars/avatar_hekim.png',
    ),
    CosmeticItem(
      id: 'avatar_okur_bilge',
      name: 'Asker Lugo',
      description: '',
      type: CosmeticType.avatar,
      price: 500,
      previewValue: 'assets/images/avatars/avatar_okur_bilge.png',
    ),
    CosmeticItem(
      id: 'avatar_hazine_avcisi',
      name: 'Hazine Avcısı',
      description: '',
      type: CosmeticType.avatar,
      price: 500,
      previewValue: 'assets/images/avatars/avatar_hazine_avcisi.png',
    ),
    CosmeticItem(
      id: 'avatar_muhendis',
      name: 'Mühendis',
      description: '',
      type: CosmeticType.avatar,
      price: 500,
      previewValue: 'assets/images/avatars/avatar_muhendis.png',
    ),
    CosmeticItem(
      id: 'avatar_arastirmaci',
      name: 'Araştırmacı',
      description: '',
      type: CosmeticType.avatar,
      price: 500,
      previewValue: 'assets/images/avatars/avatar_arastirmaci.png',
    ),
    CosmeticItem(
      id: 'avatar_serif',
      name: 'Şerif',
      description: '',
      type: CosmeticType.avatar,
      price: 500,
      previewValue: 'assets/images/avatars/avatar_serif.png',
    ),
    CosmeticItem(
      id: 'avatar_mucit',
      name: 'Mucit',
      description: '',
      type: CosmeticType.avatar,
      price: 500,
      previewValue: 'assets/images/avatars/avatar_mucit.png',
    ),
    CosmeticItem(
      id: 'avatar_premium_l_kahraman',
      name: 'Super Lugo',
      description: '',
      type: CosmeticType.avatar,
      price: 2000,
      previewValue: 'assets/images/avatars/avatar_premium_l_kahraman.png',
      isPremiumOnly: true,
    ),
    CosmeticItem(
      id: 'avatar_premium_siber_kahraman',
      name: 'Siber Kahraman',
      description: '',
      type: CosmeticType.avatar,
      price: 2000,
      previewValue: 'assets/images/avatars/avatar_premium_siber_kahraman.png',
      isPremiumOnly: true,
    ),
    // Yiyecek Temalı (Eğlenceli)
    CosmeticItem(
      id: 'avatar_pizza',
      name: 'Pizza',
      description: '',
      type: CosmeticType.avatar,
      price: 100,
      previewValue: '🍕',
    ),
    CosmeticItem(
      id: 'avatar_icecream',
      name: 'Dondurma',
      description: '',
      type: CosmeticType.avatar,
      price: 100,
      previewValue: '🍦',
    ),
    CosmeticItem(
      id: 'avatar_cupcake',
      name: 'Cupcake',
      description: '',
      type: CosmeticType.avatar,
      price: 120,
      previewValue: '🧁',
    ),
    CosmeticItem(
      id: 'avatar_burger',
      name: 'Burger',
      description: '',
      type: CosmeticType.avatar,
      price: 100,
      previewValue: '🍔',
    ),
    CosmeticItem(
      id: 'avatar_donut',
      name: 'Donut',
      description: '',
      type: CosmeticType.avatar,
      price: 100,
      previewValue: '🍩',
    ),
    CosmeticItem(
      id: 'avatar_taco',
      name: 'Taco',
      description: '',
      type: CosmeticType.avatar,
      price: 100,
      previewValue: '🌮',
    ),
    CosmeticItem(
      id: 'avatar_popcorn',
      name: 'Patlamış Mısır',
      description: '',
      type: CosmeticType.avatar,
      price: 100,
      previewValue: '🍿',
    ),
    CosmeticItem(
      id: 'avatar_bubble_tea',
      name: 'Bubble Tea',
      description: '',
      type: CosmeticType.avatar,
      price: 100,
      previewValue: '🧋',
    ),

    // ===== EMOJİLER (Maç İçi İfadeler) =====
    CosmeticItem(
      id: 'emote_laugh',
      name: 'Kahkaha',
      description: 'Rakibinin hatasına gül',
      type: CosmeticType.emote,
      price: 500,
      previewValue: '😂',
    ),
    CosmeticItem(
      id: 'emote_angry',
      name: 'Kızgın',
      description: 'Şansı yaver gitmediğinde',
      type: CosmeticType.emote,
      price: 500,
      previewValue: '😡',
    ),
    CosmeticItem(
      id: 'emote_cry',
      name: 'Ağlayan',
      description: 'Yanlış cevap verdikten sonra',
      type: CosmeticType.emote,
      price: 500,
      previewValue: '😭',
    ),
    CosmeticItem(
      id: 'emote_mind_blown',
      name: 'Şaşkın',
      description: 'İnanılmaz bir cevap geldiğinde',
      type: CosmeticType.emote,
      price: 500,
      previewValue: '🤯',
    ),
    CosmeticItem(
      id: 'emote_cool',
      name: 'Havalı',
      description: 'Seriye bağladığında',
      type: CosmeticType.emote,
      price: 500,
      previewValue: '😎',
    ),
  ];
}
