# Flutter iOS Podfile
platform :ios, '13.0'

import '../../.flutter-plugins-dependencies' if File.exist?('../../.flutter-plugins-dependencies')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__file__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Codemagic ve Firebase uyumluluğu için minimum deployment target'ı burada da zorunlu kılıyoruz
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end